sudo: required
language: go

go:
  - 1.13.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - $GOPATH/pkg/mod

script:
  - make test
  - make verify-codegen
  - make build
  - make e2e

after_success:
  - if [ ! -s "$TRAVIS_TAG" ] ; then
      docker tag openfaas/openfaas-operator:latest openfaas/openfaas-operator:$TRAVIS_TAG;
      echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
      docker push openfaas/openfaas-operator:$TRAVIS_TAG;

      docker tag openfaas/openfaas-operator:latest quay.io/openfaas/openfaas-operator:$TRAVIS_TAG;
      echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
      docker push quay.io/openfaas/openfaas-operator:$TRAVIS_TAG;
    fi
