sudo: required
language: go

go:
  - 1.9.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - echo "Please don't go get"

script:
  - docker build -t functions/faas-o6a:latest-dev .

after_success:
  - if [ -z "$DOCKER_USER" ]; then
      echo "PR build, skipping Docker Hub push";
    else
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      docker push functions/faas-o6a:latest-dev;
    fi
