required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.11"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.6.0"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.7.5"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"
