required = ["k8s.io/code-generator/cmd/client-gen"]

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-7.0"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/gengo"
  revision = "9e661e9308f078838e266cca1c673922088c0ea4"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.5.0"

[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.7.5"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"
