apiVersion: o6s.io/v1alpha1
kind: Function
metadata:
  name: gofast
  namespace: openfaas-fn
spec:
  name: gofast
  replicas: 2
  image: alexellis/gofast023
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "5"
  environment:
    output: "verbose"
    debug: "true"
  secrets:
    - faas-token
    - faas-key
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "10m"
    memory: "64Mi"
  constraints:
    - "cloud.google.com/gke-nodepool=default-pool"
