apiVersion: o6s.io/v1alpha1
kind: Function
metadata:
  name: nodeinfo
spec:
  name: nodeinfo
  replicas: 2
  handler: node main.js
  image: functions/nodeinfo
  labels:
    com.openfaas.scale.min: "2"
    com.openfaas.scale.max: "15"
  environment:
    output: "verbose"
    debug: "true"
  limits:
    cpu: "2"
    memory: "1Gi"
  requests:
    cpu: "0.1"
    memory: "128Mi"
  constraints:
    - "cloud.google.com/gke-nodepool=default-pool"
