---
apiVersion: v1
kind: Service
metadata:
  name: faas-o6s
  namespace: openfaas
  labels:
    app: faas-o6s
spec:
  type: ClusterIP
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: faas-o6s
