apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: functions.o6s.io
spec:
  group: o6s.io
  version: v1alpha1
  names:
    kind: Function
    plural: functions
  scope: Namespaced
