apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: functions.openfaas.com
spec:
  group: openfaas.com
  version: v1alpha2
  names:
    kind: Function
    plural: functions
  scope: Namespaced
